### ISSUE TITLE
The Code to your bio ..

### ISSUE THREAD

**Issue by Jarad999** [Itz-Hyperz/Itz-Hyperz#3]
for anyone who wonders how hyperz ~~the nerd~~ coded bio thingy looks .. 

"What's up weirdos, I'm a highschooler with a passion for Software Development and Graphic Design!  I spend most of my time coding in Discord calls with friends, or playing games on Steam.  Currently I am Sleeping, while writing Eating on Coding"

**Comment by Itz-Hyperz** [comment]
1), That is not how it would look, the randomize function clearly separates specific pieces of the array
2), This is not an issue.
3), JuiceWRLD sucks
