### ISSUE TITLE
False Advertisements 

### ISSUE THREAD

**Issue by braxtongpoll** [Itz-Hyperz/Itz-Hyperz#6]
States developer is fully self taught from online resources, when this is only partially true.

**Comment by JakeHamblin** [comment]
Dude learned on a tin-can. Not sure why he's lying.

**Comment by Itz-Hyperz** [comment]
> States developer is fully self taught from online resources, when this is only partially true.

half the shit you taught me you didn't answer until I bugged you, and just to restate, you are someone I met online, you were a resource I used, that makes you an online resource.
